---
- name: Configure Xray server in docker ( all-in-one )
  hosts: all
  become: true
  vars_files:
    - vars.yml

  tasks:
    
    - block:  
      - name: Set Polycy
        ansible.builtin.iptables:
          chain: '{{ item }}'
          policy: ACCEPT
        with_items: ['INPUT', 'FORWARD', 'OUTPUT']

      - name: Flush all
        ansible.builtin.iptables:
          chain: '{{ item }}'
          flush: yes
        with_items: ['INPUT', 'FORWARD', 'OUTPUT']

      - name: Flush nat
        ansible.builtin.iptables:
          chain: '{{ item }}'
          flush: yes
          table: nat
        with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]
       
      - name: Allow related and established connections
        ansible.builtin.iptables:
          chain: INPUT
          ctstate: ESTABLISHED,RELATED
          jump: ACCEPT

      - name: match on ip ranges
        ansible.builtin.iptables:
          chain: forward
          in_interface: "{{ ansible_default_ipv4.interface }}"
          out_interface: br-+
          jump: accept

      - name: deny PING
        ansible.builtin.iptables:
          chain: INPUT
          protocol: icmp
          jump: DROP

      - name: Set tcp flags
        ansible.builtin.iptables:
          chain: OUTPUT
          jump: DROP
          protocol: tcp
          tcp_flags:
            flags: ALL
            flags_set:
              - ACK
              - RST
              - SYN
              - FIN
          
      - name: allow 22, 80, 443, 54320, 54327, 54328 ports
        ansible.builtin.iptables:
          chain: INPUT
          protocol: tcp
          destination_ports:
           - '22'
           - '80'
           - '443'
           - '54320'
           - '54327'
           - '54328'
          jump: ACCEPT

      - name: Drop others input
        ansible.builtin.iptables:
          chain: INPUT
          jump: DROP

      - name: Save current state of the firewall in system file for ipv4
        community.general.iptables_state:
          state: saved
          path: /etc/iptables/rules.v4

      - name: Save current state of the firewall in system file for ipv6
        community.general.iptables_state:
          ip_version: ipv6
          state: saved
          path: /etc/iptables/rules.v6
      
