---
- name: Configure OpenConnect Server (ocserv)
  hosts: all
  become: true
  vars_files:
    - vars.yml
 
  tasks:

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name: 
          - certbot
        state: present

    - name: Set net.core.default_qdisc in sysctl
      sysctl:
        name: net.core.default_qdisc
        value: fq
        sysctl_set: yes
        state: present
        reload: yes
  
    - name: Set net.ipv4.tcp_congestion_control in sysctl
      sysctl:
	name: net.ipv4.tcp_congestion_control
        value: bbr
        sysctl_set: yes
        state: present
        reload: yes

    
    - name: Generate SSL certificate using Certbot
      ansible.builtin.command:
        cmd: >
          certbot certonly --dry-run --standalone --noninteractive --agree-tos --email {{ email }} --domain {{ domain_name }}
      args:
        creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name: 
          - ocserv
        state: present

    - name: Create configuration directory if not exists
      ansible.builtin.file:
        path: /etc/ocserv
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Deploy ocserv configuration file
      ansible.builtin.template:
        src: templates/ocserv.conf.j2
        dest: /etc/ocserv/ocserv.conf
        owner: root
        group: root
        mode: '0644'

    - name: Ensure ocserv service is enabled and started
      ansible.builtin.systemd:
        name: ocserv
        enabled: true
        state: started
